version: '3.9'

services:
  strm-manager:
    build: .
    container_name: strm-manager
    ports:
      - "5001:5001"
    volumes:
      - ../robofuse/Library:/app/Library
      - ../robofuse/processed_paths.json:/app/processed_paths.json
    restart: unless-stopped
