version: '3.9'

services:
  strm-manager:
    build: .
    container_name: strm-manager
    ports:
      - "5001:5001"
    volumes:
      - ../robofuse/Library:/app/Library
    restart: unless-stopped
